### ISSUE TITLE
Provide CI Tests via GitHub Action

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/mobile-app#1]
**As a** software developer,
**I need** A CI-Pipeline
**so that** I can check that basic the consistency of the code style (linting) and the success of a basic test suite (integration test).

### AK
- [x] Linting is run on every commit for Svelte and NativeScript code
- [ ] Integration test is run for every commit on main + PRs

**Comment by leo-3108** [comment]
@finnge @patrickraullang Wie ist hier der Stand? Wollt ihr das noch fertig machen?

**Comment by finnge** [comment]
Mind. für BC müsste das von @patrickraullang noch fertig gemacht werden.
