### ISSUE TITLE
Spezifikation von Reise-Informationen für Planung

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/mobile-app#2]
**Als** Nutzer:in
**muss ich** Informationen (Start- oder Endzeitpunkt, Start- und/oder Endort, präferierte Routenoption) zu meiner Reise spezifizieren,
**damit ich** die für mich passende Route finden kann.

- [ ] #3 

### Anforderungen
- **A22:** Das System muss dem:der Nutzer:in die Möglichkeit bieten, seine:ihre Reisepräferenzen (kurze Reise, wenig Umsteigen, Günstig/bestehendes Abo, geringer ökologischer Fußabdruck, Auslastung, naturgebundene Routen, schöne Routen) mitteilen zu können.

### GUI-Konzepte

<div>
<table>
<tr>
<th>1</th><th>2</th><th>3</th>
</tr>
<tr>
<td>
<img width="390" alt="card-reiseplanung-1" src="https://user-images.githubusercontent.com/19761338/235447531-2bf9b164-9ce1-4a3c-97ae-51ed83382eb1.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-2" src="https://user-images.githubusercontent.com/19761338/235447539-0eb86541-4675-4dd0-b493-675f76c0a9af.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-3" src="https://user-images.githubusercontent.com/19761338/235447548-dfd75aba-f249-42ea-8a41-ef082dc63e84.png">
</td>
</tr>
<tr>
<th>4</th><th>5</th><th>6</th>
</tr>
<tr>
<td>
<img width="390" alt="card-reiseplanung-4" src="https://user-images.githubusercontent.com/19761338/235447510-b2ffbe68-40bf-416c-8ec2-794a4961cbae.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-5" src="https://user-images.githubusercontent.com/19761338/235447561-ad696fec-2129-4388-a89b-bb23bb775938.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-6" src="https://user-images.githubusercontent.com/19761338/235447573-d74d77fd-6a37-4239-b160-10bf5d7df5a1.png">
</td>
</tr>
<tr>
<th>7</th><th>8</th><th>9</th>
</tr>
<tr>
<td>
<img width="390" alt="card-reiseplanung-7" src="https://user-images.githubusercontent.com/19761338/235447586-8ebcb6e9-7faa-4d29-82f1-8a4f0fec7fe0.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-8" src="https://user-images.githubusercontent.com/19761338/235447597-110d0cc9-9763-4b54-a4fe-5068fc03a7b6.png">
</td>
<td>
<img width="390" alt="card-reiseplanung-9" src="https://user-images.githubusercontent.com/19761338/235447613-c28e1405-37af-48e9-98f0-b9b7f0219238.png">
</td>
</tr>
</table>
</div>

**Comment by Libao1** [comment]
**Spezifikation der Reise-Informationen**

Aktuelle Umsetzung:
- Nachdem Nutzer:innen einen Zielort eingegeben haben und die Reise für einen späteren Zeitpunkt geplant wird, sind die nachfolgenden Schritte unerwartet. Dies kann Nutzer:innen während des Prozesses verunsichern und die Nachvollziehbarkeit erschweren.
- Bei der Eingabe von Präferenzen während einer Planung einer Route/Reise, wird nicht deutlich, dass es hier Interaktionsmöglichkeiten gibt und eine Auswahl getroffen werden kann. Ein entsprechender Indikator fehlt. Zusätzlich wird nicht spezifiziert wie viele Optionen ausgewählt werden können
- Bei der Auswahl vorgeschlagener Routen-Optionen wird die Darbietung und damit auch die Auswahl weiterer Optionen erschwert.
- Die Ankunftszeit bei der Auswahl einer Route ist nicht eindeutig spezifiziert, was für Nutzer:innen irreführend sein kann. So ist nicht eindeutig, ob die angezeigte Zeit die Ankunfts- oder Aufbruchszeitdarstellt.

Gewünschte Umsetzung:
- Hier sollte die Reihenfolge der Schritte für den Prozess einer Reiseplanung überdacht werden. Ähnliche Systeme auf dem Markt können hierbei eine Referenz bilden.
- Es sollte mit den Nutzer:innen kommuniziert werden, dass und wie viele Optionen ausgewählt werden können. Dies kann sowohl visuell als auch auditiv geschehen.
- Zentral sollten die Optionen vorgeschlagen werden, die den Nutzer:innen am hilfreichsten sein kann. Darüber hinaus wären Vorschläge für frühere und spätere Optionen sinnvoll.
- Es sollte zu an jedem Punkt genau spezifiziert werden, ob es sich bei der angezeigten Zeit um die Aufbrauchs- oder Ankunftszeit handelt. 


GUI-Konzept:
